// check_error 4:5 "no matching function for call to 'f'"
func f(int a) { }
func main() {
    f(foo: 0);
}
