// check_error 3:6 "redefinition of 'foo'"
func foo() { }
func foo() { }
